# Generated by Django 3.2.23 on 2024-02-07 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='caption',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='post_image',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='tags',
        ),
    ]
